name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:


  ubuntu-build:
    name: Ubuntu build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup build folders
        run: |
          mkdir build
          mkdir build/Ubuntu
      - name: build
        run: |
          make BUILDDIR=build/Ubuntu/ EXECDIR=build/Ubuntu/
      - name: make things easy for the non devs
        run: |
          cd build/Ubuntu
          tar -cf The_objects_files.tar *.o --remove-files
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: healthmeter_build_ubuntu
          path: build

  macos-x-build:
    runs-on: macOS-latest
    name: Mac OS X build
    steps:
      - uses: actions/checkout@v4
      - name: setup build folders
        run: |
          mkdir build
          mkdir build/MacOS
      - name: build
        run: |
          make BUILDDIR=build/MacOS/ EXECDIR=build/MacOS/
      - name: make things easy for the non devs
        run: |
          cd build/MacOS
          tar -cf The_objects_files.tar *.o
          rm -f *.o
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: healthmeter_build_macos_x
          path: build

  windows-build:
    runs-on: ubuntu-latest
    name: Windows build
    steps:
      - uses: actions/checkout@v4
      - name: Windows env
        run: |
          sudo apt-get install mingw-w64
      - name: setup build folders
        run: |
          mkdir build
          mkdir build/Windows
      - name: build
        run:
          make CXX=x86_64-w64-mingw32-g++-posix  BUILDDIR=build/Windows/ EXECDIR=build/Windows/
      - name: make things easy for the non devs
        run: |
          cd build/Windows
          tar -cf The_objects_files.tar *.o --remove-files
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: healthmeter_build_windows
          path: build


  merge:
    runs-on: ubuntu-latest
    needs: [ windows-build, ubuntu-build, macos-x-build ] 
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
          name: healthmeter_builds
